In [2]:
import numpy as np

In [5]:
lst = [1,2,3,4]

arr = np.array(lst)
print(arr)

[1 2 3 4]


In [7]:
lst = [1.5, "String", True]
arr = np.array(lst)
print(arr)

['1.5' 'String' 'True']


In [10]:
from sys import getsizeof

lst = []
print(getsizeof(lst))

arr = np.array(lst)
print(getsizeof(arr))

56
104


In [12]:
prices = [30,25,40,20,20,35,50,35]

new_prices = [price-5 for price in prices]
print(new_prices)

prices_arr = np.array(prices)
prices_arr = prices_arr - 5
print(prices_arr)

[25, 20, 35, 15, 15, 30, 45, 30]
[25 20 35 15 15 30 45 30]


In [23]:
#exer

test_1 = np.array([92, 94, 88, 91, 87])
test_2 = np.array([79, 100, 86, 93, 91])
test_3 = np.array([87, 85, 72, 90, 92])

test_3_fixed = test_3 +2
print(test_3_fixed)

total_grade = test_1+test_2+test_3_fixed
print(total_grade)

final_grade = total_grade / 3
print(final_grade)

jeremy_test_2 = test_2[3]
print(jeremy_test_2)

manual_adwoa_test_1 = np.array([test_1[1], test_1[2]])
print(manual_adwoa_test_1)

student_scores = np.array([test_1, test_2, test_3])
print(student_scores)

print(student_scores[2, 0])

print(student_scores[:, 4])

[89 87 74 92 94]
[260 281 248 276 272]
[86.66666667 93.66666667 82.66666667 92.         90.66666667]
93
[94 88]
[[ 92  94  88  91  87]
 [ 79 100  86  93  91]
 [ 87  85  72  90  92]]
87
[87 91 92]


In [28]:
a = np.array([10, 2, 2, 4, 5, 3, 9, 8, 9, 7])
mask = a > 5
print(mask)

selected = a[a > 5]
print(selected)

selected = a[(a > 6) | (a < 4)]
print(selected)

selected = a[(a > 4)&(a < 8)]
print(selected)

[ True False False False False False  True  True  True  True]
[10  9  8  9  7]
[10  2  2  3  9  8  9  7]
[5 7]


In [33]:
porridge = np.array([79, 65, 50, 63, 56, 90, 85, 98, 79, 51])
cold = porridge[porridge < 60]
hot = porridge[porridge > 80]
just_right = porridge[(porridge >= 60) | (porridge <= 80)]
print(cold)
print(hot)
print(just_right)

[50 56 51]
[90 85 98]
[79 65 50 63 56 90 85 98 79 51]
