In [2]:
import numpy as np

In [3]:
porridge = np.array([79, 65, 50, 63, 56, 90, 85, 98, 79, 51])
cold = porridge[porridge < 60]
hot = porridge[porridge > 80]
just_right = porridge[(porridge >= 60) | (porridge <= 80)]
print(cold)
print(hot)
print(just_right)

[50 56 51]
[90 85 98]
[79 65 50 63 56 90 85 98 79 51]
